MusicalShop.App/Controllers/CartController.cs
namespace MusicalShop.App.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using MusicalShop.Services;
    using MusicalShop.Services.Mapping;
    using MusicalShop.Web.ViewModels.Order;
    using System;
    using System.Threading.Tasks;
    using System.Linq;
    using System.Collections.Generic;

    public class CartController : Controller
    {
        private readonly IProductService productService;

        public CartController(IProductService productService)
        {
            this.productService = productService;
        }

        public async Task<IActionResult> Cart()
        {
            if (!this.User.Identity.IsAuthenticated)
            {
                return this.Redirect("/Identity/Account/Register");
            }

            var products = await GetProductsFromCookies();
            decimal price = 0;
            products.ToList().ForEach(p => price += p.Price * p.Quntity);
            ViewData["price"] = price;

            return this.View(products);
        }

        public async Task<IActionResult> Checkout()
        {
            var products = await GetProductsFromCookies();
            decimal price = 0;
            products.ToList().ForEach(p => price += p.Price * p.Quntity);
            ViewData["price"] = price;
            return this.View();
        }
        public async Task<List<CartViewModel>> GetProductsFromCookies()
        {
            var cookies = Request.Cookies.Where(x => x.Key.Contains("product"));
            var products = new List<CartViewModel>();

            foreach (var cookie in cookies)
            {
                var parametres = cookie.Value.Split(new[] { ' ', ':' }, StringSplitOptions.RemoveEmptyEntries);
                var id = parametres[1];
                var qty = int.Parse(parametres[3]);

                var product = (await productService.GetProductByIdAsync(id)).To<CartViewModel>();
                product.Quntity = qty;
                products.Add(product);
            }

            return products;
        }
        [HttpGet("Cart/Remove/{id?}")]
        public async Task<IActionResult> Remove(string id)
        {
            var key = Request.Cookies.SingleOrDefault(x => x.Value.Contains(id)).Key;
            Response.Cookies.Delete(key);
            return this.Redirect("/Cart/Cart");
        }
    }
}

MusicalShop.App/Controllers/ProductController.cs
namespace MusicalShop.App.Controllers
{
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using MusicalShop.Services;
    using MusicalShop.Services.Mapping;
    using MusicalShop.Web.InputModels.Product;
    using MusicalShop.Web.ViewModels;
    using MusicalShop.Web.ViewModels.Shop;
    using System;
    using System.Threading.Tasks;
    using System.Linq;

    public class ProductController : Controller
    {
        private readonly IProductService productService;
        public ProductController(IProductService productService)
        {
            this.productService = productService;
        }

        [HttpGet("Product/Details/{id?}")]
        public async Task<IActionResult> Details(string id)
        {
            var productDetailsViewModel = (await productService.GetProductByIdAsync(id)).To<ProductDetailsViewModel>();

            if (productDetailsViewModel.Quantity <= 0)
            {
                productDetailsViewModel.IsInStock = false;
            }

            return this.View(productDetailsViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Shop()
        {
            var products = productService.GetAllProducts().To<ProductShopViewModel>();
            var productTypes = productService.GetAllProductTypes().To<ProductTypeViewModel>();
            var productBrands = productService.GetAllProductBrands().To<ProductBrandViewModel>();

            ViewData["types"] = productTypes;
            ViewData["brands"] = productBrands;

            return this.View(products);
        }

        [HttpGet("Product/Brand/{brand?}")]
        public async Task<IActionResult> Brand(string brand)
        {
            var products = productService.GetAllProductsByBrand(brand).To<ProductShopViewModel>();
            var productBrands = productService.GetAllProductBrands().To<ProductBrandViewModel>();
            var productTypes = productService.GetAllProductTypes().To<ProductTypeViewModel>();

            ViewData["types"] = productTypes;
            ViewData["brands"] = productBrands;
         
            return this.View("Shop", products);
        }

        [HttpGet("Product/Type/{type?}")]
        public async Task<IActionResult> Type(string type)
        {
            var products = productService.GetAllProductsByType(type).To<ProductShopViewModel>();
            var productBrands = productService.GetAllProductBrands().To<ProductBrandViewModel>();
            var productTypes = productService.GetAllProductTypes().To<ProductTypeViewModel>();

            ViewData["types"] = productTypes;
            ViewData["brands"] = productBrands;

            return this.View("Shop", products);
        }

      /*  [HttpGet("Product/Price/{minPrice?}/{maxPrice?}")]
        public async Task<IActionResult> Price(decimal minPrice, decimal maxPrice)
        {
            var products = productService.GetAllProductsByPrice(minPrice, maxPrice).To<ProductShopViewModel>();
            var productBrands = productService.GetAllProductBrands().To<ProductBrandViewModel>();
            var productTypes = productService.GetAllProductTypes().To<ProductTypeViewModel>();

            ViewData["types"] = productTypes;
            ViewData["brands"] = productBrands;

            return this.View("Shop", products);
        }*/
        [HttpPost]
        public async Task<IActionResult> AddToCart([FromForm] ProductCartInputModel model)
        {
            if (!this.User.Identity.IsAuthenticated)
            {
                return this.Redirect("/Identity/Account/Login");
            }

            var key = "product" + Guid.NewGuid().ToString();
            var value = $"Id:{model.Id} Qty:{model.Quantity}";

            var responseCookie = Request.Cookies.FirstOrDefault(x => x.Key.Contains("product") && x.Value.Contains(model.Id));

            if (responseCookie.Key != null)
            {
                var qty = int.Parse(responseCookie.Value.Split(new[] { ' ', ':' }, StringSplitOptions.RemoveEmptyEntries)[3]) + model.Quantity;
                key = responseCookie.Key;
                value = $"Id:{model.Id} Qty:{qty}";
            }

            var cookieOpts = new CookieOptions();
            cookieOpts.Expires = DateTime.UtcNow.AddDays(7);
            
            Response.Cookies.Append(key, value, cookieOpts);

            return this.Redirect("/");
        }

        [HttpGet("Product/Wishlist/{id?}")]
        public async Task<IActionResult> AddToWishlist(string id)
        {
            if (!this.User.Identity.IsAuthenticated)
            {
                return this.Redirect("/Identity/Account/Login");
            }

            var key = "wish" + Guid.NewGuid().ToString();
            var value = id;
            var responseCookie = Request.Cookies.FirstOrDefault(x => x.Value == id);
            if (responseCookie.Key == null)
            {
                var cookieOpts = new CookieOptions();
                cookieOpts.Expires = DateTime.UtcNow.AddDays(7);
                var cookie = Request.Cookies[key];

                Response.Cookies.Append(key, value, cookieOpts);
            }

            return this.Redirect("/");
        }
    }
}

MusicalShop.App/Controllers/WishlistController.cs
namespace MusicalShop.App.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using MusicalShop.Services;
    using MusicalShop.Services.Mapping;
    using MusicalShop.Web.ViewModels.Wishlist;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    public class WishlistController : Controller
    {
        private readonly IProductService productService;

        public WishlistController(IProductService productService)
        {
            this.productService = productService;
        }
        public async Task<IActionResult> Wishlist()
        {
            var wishes = await GetProductsFromCookies();
            return this.View(wishes);
        }
        public async Task<List<WishlistViewModel>> GetProductsFromCookies()
        {
            var cookies = Request.Cookies.Where(x => x.Key.Contains("wish"));
            var wishes = new List<WishlistViewModel>();

            foreach (var cookie in cookies)
            { 
                var id = cookie.Value;

                if (!wishes.Where(x => x.Id == id).Any())
                {
                    var wish = (await productService.GetProductByIdAsync(id)).To<WishlistViewModel>();
                    wishes.Add(wish);
                }
            }

            return wishes;
        }
        [HttpGet("Wishlist/Remove/{id?}")]
        public async Task<IActionResult> RemoveWish(string id)
        {
            var cookie = Request.Cookies.SingleOrDefault(x => x.Value == id);
            var key = cookie.Key;
            Response.Cookies.Delete(key);
            return this.Redirect("/Wishlist/Wishlist");
        }
    }
}

MusicalShop.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <!-- Title  -->
    <title>PulseMS</title>

    <!-- Favicon  -->
    <link rel="icon" href="~/img/sound.png">

    <!-- Core Style CSS -->
    <link rel="stylesheet" href="">
    <link rel="stylesheet" href="~/css/core-style.css">
    <link rel="stylesheet" href="~/style.css">

</head>

<body>
    <!-- Search Wrapper Area Start -->
    <div class="search-wrapper section-padding-100">
        <div class="search-close">
            <i class="fa fa-close" aria-hidden="true"></i>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="search-content">
                        <form action="#" method="get">
                            <input type="search" name="search" id="search" placeholder="Type your keyword...">
                            <button type="submit"><img src="img/core-img/search.png" alt=""></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Search Wrapper Area End -->
    <!-- ##### Main Content Wrapper Start ##### -->
    <div class="main-content-wrapper d-flex clearfix">

        <!-- Mobile Nav (max width 767px)-->
        <div class="mobile-nav">
            <!-- Navbar Brand -->
            <div class="amado-navbar-brand">
                <a href="#"><img src="~/img/sound.png" alt=""></a>
            </div>
            <!-- Navbar Toggler -->
            <div class="amado-navbar-toggler">
                <span></span><span></span><span></span>
            </div>
        </div>

        <!-- Header Area Start -->
        <header class="header-area clearfix">
            <!-- Close Icon -->
            <div class="nav-close">
                <i class="fa fa-close" aria-hidden="true"></i>
            </div>
            <!-- Logo -->
            <div class="logo">
                <a asp-controller="Home" asp-action="Index"><img src="~/img/guitar.png" alt=""></a>
            </div>
            <!-- Amado Nav -->
            <nav class="amado-nav">
                <ul>
                    <li><a href="/">Home</a></li>
                    <li><a asp-controller="Product" asp-action="Shop">Shop</a></li>
                    <li><a asp-controller="Cart" asp-action="Cart">Cart</a></li>
                    <li class="active"><a asp-controller="Cart" asp-action="Checkout">Checkout</a></li>
                </ul>
            </nav>
            <!-- Button Group -->
            <div class="amado-btn-group mt-30 mb-100">
                <a href="#" class="btn amado-btn mb-15">%Discount%</a>
                <a href="#" class="btn amado-btn active">New this week</a>
            </div>
            <!-- Cart Menu -->
            <div class="cart-fav-search mb-100">
                <a asp-controller="Cart" asp-action="Cart" class="cart-nav"><img src="~/img/core-img/cart.png" alt=""> Cart <span>(0)</span></a>
                <a asp-controller="Wishlist" asp-action="Wishlist" class="fav-nav"><img src="~/img/core-img/favorites.png" alt=""> Favourite</a>
                <a href="#" class="search-nav"><img src="~/img/core-img/search.png" alt=""> Search</a>

                @if (this.User.IsInRole("Admin"))
                {
    <div class="dropdown">
        <a class="dropdown-toggle"
           id="dropdownMenu"
           data-toggle="dropdown"
           aria-haspopup="true"
           aria-expanded="false">
            <img src="~/img/unauthorized-person.png">Admin
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenulink">
            <a class="dropdown-item" href="/Administration/Product/Create">Create Product</a>
            <a class="dropdown-item-text" href="/Administration/Product/Type/Create">Create Type</a>
            <a class="dropdown-item-text" href="/Administration/Product/Brand/Create">Create Brand</a>

        </div>
    </div>}

                @if (!this.User.Identity.IsAuthenticated)
                {
    <a href="/Identity/Account/Register" class="search-nav">
        <img src="~/img/edit.png" alt="">Register
    </a>

                    <a href="/Identity/Account/Login" class="fav-nav">
                        <img src="~/img/user.png" alt="">Login
                    </a>}
                @if (this.User.Identity.IsAuthenticated)
                {
    <a href="/Identity/Account/Logout" class="fav-nav">
        <img src="~/img/logout.png" alt="">Logout
    </a>}
            </div>
            <!-- Social Button -->
            <div class="social-info d-flex justify-content-between">
                <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
            </div>
        </header>
        <!-- Header Area End -->
        @RenderBody()
    </div>
    <section class="newsletter-area section-padding-100-0">
        <div class="container">
            <div class="row align-items-center">
                <!-- Newsletter Text -->
                <div class="col-12 col-lg-6 col-xl-7">
                    <div class="newsletter-text mb-100">
                        <h2>Subscribe for a <span>25% Discount</span></h2>
                        <p>Nulla ac convallis lorem, eget euismod nisl. Donec in libero sit amet mi vulputate consectetur. Donec auctor interdum purus, ac finibus massa bibendum nec.</p>
                    </div>
                </div>
                <!-- Newsletter Form -->
                <div class="col-12 col-lg-6 col-xl-5">
                    <div class="newsletter-form mb-100">
                        <form action="#" method="post">
                            <input type="email" name="email" class="nl-email" placeholder="Your E-mail">
                            <input type="submit" value="Subscribe">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Newsletter Area End ##### -->
    <!-- ##### Footer Area Start ##### -->
    <footer class="footer_area clearfix">
        <div class="container">
            <div class="row align-items-center">
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-4">
                    <div class="single_widget_area">
                        <!-- Logo -->
                        @*<div class="footer-logo mr-50">
                            <a href="/"><img src="~/img/33178639.jpg" alt=""></a>
                        </div>*@
                        <!-- Copywrite Text -->
                        <p class="copywrite">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a> & Re-distributed by <a href="https://themewagon.com/" target="_blank">Themewagon</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-8">
                    <div class="single_widget_area">
                        <!-- Footer Menu -->
                        <div class="footer_menu">
                            <nav class="navbar navbar-expand-lg justify-content-end">
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#footerNavContent" aria-controls="footerNavContent" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
                                <div class="collapse navbar-collapse" id="footerNavContent">
                                    <ul class="navbar-nav ml-auto">
                                        <li class="nav-item active">
                                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" asp-controller="Product" asp-action="Shop">Shop</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" asp-controller="Cart" asp-action="Cart">Cart</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" asp-controller="Cart" asp-action="Checkout">Checkout</a>
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ##### Footer Area End ##### -->
    <script src="~/js/jquery/jquery-2.2.4.min.js" asp-append-version="true"></script>
    <script src="~/js/popper.min.js" asp-append-version="true"></script>
    <script src="~/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/plugins.js" asp-append-version="true"></script>
    <script src="~/js/active.js"  asp-append-version="true"></script>
    <script src="~/js/cart.js"  asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>